### ISSUE TITLE
DUA does not seem correct with 2 members and %(M/N)

### ISSUE THREAD

**Issue by c-geek** [libre-money-projects/trm_charts#2]
As you can see, I have 2 members with 100% of M/N each. This mean we have M = 200%, which is not the correct definition I think: M = 100% would be better.

![image](https://cloud.githubusercontent.com/assets/969136/19432054/21615bb8-945b-11e6-8fb0-c970208121f2.png)

**Comment by cuckooland** [comment]
If I well see: 2 members have each one 100% of M/2, which is correct?
Sorry if I say an enormity, I have to fight to keep my eyes opened...

**Comment by c-geek** [comment]
OK sorry, I just did not get it. 100% of M/N yes ... it is just normal. I was thinking in quantitative way.
